import { KeyItem } from "@/types/keyboard";

export const keyboardRows: KeyItem[][] = [
  [
    { label: '`', code: 'Backquote', value: '`' },
    { label: '1', code: 'Digit1', value: '1' },
    { label: '2', code: 'Digit2', value: '2' },
    { label: '3', code: 'Digit3', value: '3' },
    { label: '4', code: 'Digit4', value: '4' },
    { label: '5', code: 'Digit5', value: '5' },
    { label: '6', code: 'Digit6', value: '6' },
    { label: '7', code: 'Digit7', value: '7' },
    { label: '8', code: 'Digit8', value: '8' },
    { label: '9', code: 'Digit9', value: '9' },
    { label: '0', code: 'Digit0', value: '0' },
    { label: '-', code: 'Minus', value: '-' },
    { label: '=', code: 'Equal', value: '=' },
    { label: 'Backspace', code: 'Backspace', className: 'min-w-28' },
  ],
  [
    { label: 'Tab', code: 'Tab', className: 'min-w-20' },
    { label: 'Q', code: 'KeyQ', value: 'q' },
    { label: 'W', code: 'KeyW', value: 'w' },
    { label: 'E', code: 'KeyE', value: 'e' },
    { label: 'R', code: 'KeyR', value: 'r' },
    { label: 'T', code: 'KeyT', value: 't' },
    { label: 'Y', code: 'KeyY', value: 'y' },
    { label: 'U', code: 'KeyU', value: 'u' },
    { label: 'I', code: 'KeyI', value: 'i' },
    { label: 'O', code: 'KeyO', value: 'o' },
    { label: 'P', code: 'KeyP', value: 'p' },
    { label: '[', code: 'BracketLeft', value: '[' },
    { label: ']', code: 'BracketRight', value: ']' },
    { label: '\\', code: 'Backslash', value: '\\' },
  ],
  [
    { label: 'Caps', code: 'CapsLock', className: 'min-w-24' },
    { label: 'A', code: 'KeyA', value: 'a' },
    { label: 'S', code: 'KeyS', value: 's' },
    { label: 'D', code: 'KeyD', value: 'd' },
    { label: 'F', code: 'KeyF', value: 'f' },
    { label: 'G', code: 'KeyG', value: 'g' },
    { label: 'H', code: 'KeyH', value: 'h' },
    { label: 'J', code: 'KeyJ', value: 'j' },
    { label: 'K', code: 'KeyK', value: 'k' },
    { label: 'L', code: 'KeyL', value: 'l' },
    { label: ';', code: 'Semicolon', value: ';' },
    { label: "'", code: 'Quote', value: "'" },
    { label: 'Enter', code: 'Enter', className: 'min-w-28' },
  ],
  [
    { label: 'Shift', code: 'ShiftLeft', className: 'min-w-32' },
    { label: 'Z', code: 'KeyZ', value: 'z' },
    { label: 'X', code: 'KeyX', value: 'x' },
    { label: 'C', code: 'KeyC', value: 'c' },
    { label: 'V', code: 'KeyV', value: 'v' },
    { label: 'B', code: 'KeyB', value: 'b' },
    { label: 'N', code: 'KeyN', value: 'n' },
    { label: 'M', code: 'KeyM', value: 'm' },
    { label: ',', code: 'Comma', value: ',' },
    { label: '.', code: 'Period', value: '.' },
    { label: '/', code: 'Slash', value: '/' },
    { label: 'Shift', code: 'ShiftRight', className: 'min-w-32' },
  ],
  [
    { label: 'Ctrl', code: 'ControlLeft', className: 'min-w-20' },
    { label: 'Alt', code: 'AltLeft', className: 'min-w-20' },
    { label: 'Space', code: 'Space', className: 'min-w-[360px]' },
    { label: 'Alt', code: 'AltRight', className: 'min-w-20' },
    { label: 'Ctrl', code: 'ControlRight', className: 'min-w-20' },
  ],
];